### ISSUE TITLE
how to add GOOGLE_REDIRECT_URL

### ISSUE THREAD

**Issue by arno608rw** [ParveenBhadooOfficial/BhadooCloud#1]
how to add GOOGLE_REDIRECT_URL

![Screen Shot 2562-03-14 at 20 47 15](https://user-images.githubusercontent.com/3774145/54361799-641c6080-469a-11e9-8286-03779d2f68af.png)

**Comment by ParveenBhadooOfficial** [comment]
Missing scheme here means http:// is missing.

to use this on local machine.

use http://localhost/oauthCallback for GOOGLE_REDIRECT_URL

**Comment by arno608rw** [comment]
OK work

**Comment by ParveenBhadooOfficial** [comment]
You have to click to upload to cloud after login with Google.

**Comment by DANGEROUSXXX** [comment]
Parveen Sir I want to get the access code of your site bhadoocloud.ga,so
plz grant me the access to upload the torrents to gdrive.

**Comment by DANGEROUSXXX** [comment]
When will the new service start?
Plz let me know coz I am in urgent need of your great service.
