### ISSUE TITLE
Unable to access instance on google cloud

### ISSUE THREAD

**Issue by doomwithdon** [ParveenBhadooOfficial/BhadooCloud#9]
I am trying to access my docker instance from an external ip.

I have followed all your instructions and here is my docker command:
docker run --name ct -d -p 80:80 --restart always -e GOOGLE_CLIENT_ID='actual client id' -e GOOGLE_CLIENT_SECRET='actual secret key' -e GOOGLE_REDIRECT_URL='http://xx.xx.xx.xx.xip.io/oauthCallback' parveenbhadoo/bhadoocloud node server/server.js --port 80

I hit my external ip which is configured on google cloud VM instance and i cannot access the application. Is there any firewall rule i am missing?

**Comment by ParveenBhadooOfficial** [comment]
I ran it on AWS Cloud. But if you're deploying on Google Cloud. Make sure you have configured IP Rules while creating a new server. Allow traffic from http and https both.

like here it was

https://i1.wp.com/hashhackers.com/wp-content/uploads/2019/06/allow-access-ssl.png

**Comment by doomwithdon** [comment]
I have done exactly that.. Still doesn't work.. Anyways i managed to run it with another method using docker images. Inwas also able to login to Google drive. Buy upload jus gets stuck on 'creating cloud directory'. No directory is created on drive though

**Comment by doomwithdon** [comment]
guess the api doesnt work anymore.. thanks anyways

**Comment by ParveenBhadooOfficial** [comment]
I don't know what problem you're facing, but at bhadoocloud.ga it works fine with current settings.
